name: Remote Deployment Dev
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install SSH Client
      run: sudo apt-get install -y sshpass

    - name: Get Short Commit Hash
      id: get_commit_hash
      run: |
        SHORT_HASH=$(git rev-parse --short=7 HEAD)
        echo "SHORT_HASH=$SHORT_HASH" >> $GITHUB_ENV
        echo "Commit Hash capturado: $SHORT_HASH"

    - name: Deploy via SSH
      env:
        SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
        SSH_USER: ${{ secrets.DEV_SSH_USER }}
        SSH_PASSWORD: ${{ secrets.DEV_SSH_PASSWORD }}
        SHORT_HASH: ${{ env.SHORT_HASH }}
      run: |
        SSHPASS=$SSH_PASSWORD sshpass -e ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
          cd /root/dev/frontend-skillfy

          # Atualizando arquivos do GitHub
          git pull origin dev

          # Debug: Exibindo hash no servidor
          echo "Hash no
