    - name: Deploy via SSH
      env:
        SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
        SSH_USER: ${{ secrets.DEV_SSH_USER }}
        SSH_PASSWORD: ${{ secrets.DEV_SSH_PASSWORD }}
        SHORT_HASH: ${{ env.SHORT_HASH }}
      run: |
        SSHPASS=$SSH_PASSWORD sshpass -e ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
          cd /root/dev/frontend-skillfy

          # Atualizando arquivos do GitHub
          git pull origin dev

          # Parar e remover o contêiner existente, se houver
          docker-compose down

          # Iniciar o contêiner sem cache
          docker-compose up -d --build

          # Esperar o contêiner subir (ajuste o tempo se necessário)
          sleep 10

          # Capturar o ID do novo contêiner
          NEW_CONTAINER_ID=$(docker ps -q --filter "name=frontend-")

          # Renomear o contêiner para incluir o commit hash
          if [ -n "$NEW_CONTAINER_ID" ]; then
            docker rename $NEW_CONTAINER_ID frontend-$SHORT_HASH
          else
            echo "Erro: Nenhum contêiner encontrado para renomear"
            exit 1
          fi
        EOF
